In [3]:
import numpy as np 

In [12]:
one_dimensional_array = np.array([1.2, 2.4, 3.5, 4.7, 6.1, 7.2, 8.3, 9.5])
print(one_dimensional_array)

[1.2 2.4 3.5 4.7 6.1 7.2 8.3 9.5]


In [5]:
two_dimensional_array = np.array([[6, 5], [11, 7], [4, 8]])
print(two_dimensional_array)

[[ 6  5]
 [11  7]
 [ 4  8]]


In [6]:
sequence_of_integers = np.arange(5, 12)
print(sequence_of_integers)

[ 5  6  7  8  9 10 11]


In [7]:
random_integers_between_50_and_100 = np.random.randint(low=50, high=101, size=(6))
print(random_integers_between_50_and_100)

[87 90 95 76 88 79]


In [13]:
random_floats_between_0_and_1 = np.random.random([6])
print(random_floats_between_0_and_1) 

[0.58497662 0.06289744 0.80966478 0.3606577  0.09674162 0.59201269]


In [14]:
random_floats_between_2_and_3 = random_floats_between_0_and_1 + 2.0
print(random_floats_between_2_and_3)

[2.58497662 2.06289744 2.80966478 2.3606577  2.09674162 2.59201269]


In [15]:
random_integers_between_150_and_300 = random_integers_between_50_and_100 * 3
print(random_integers_between_150_and_300)

[261 270 285 228 264 237]


In [18]:
#task 1

feature = np.arange(6,21)  #Question(1)    
print(feature)

label = np.random.randint(low=6, high=21, size=[15])   #Question(2)   
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[15 10 13 16  7 12 13 20 18 18 13 12 13 12  8]


In [19]:
#@title Double-click to see a possible solution to Task 1.
feature = np.arange(6, 21)
print(feature)
label = (feature * 3) + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


In [28]:
#Task 2

noise =np.random.random([5]) #Question(1)
print(noise)
label =label+noise #Question(2)
print(label)

[0.74415786 0.55748655 0.2777926  0.80289019 0.47753399]
[6.3949847  6.39202471 6.07869378 6.07039896 7.03471375]


In [29]:
#@title Double-click to see a possible solution to Task 2.

noise = (np.random.random([5]) * 4) - 2
print(noise)
label = label + noise 
print(label)

[-1.39027341 -0.55104629 -1.65801606 -1.20007995 -0.45142881]
[5.00471129 5.84097842 4.42067772 4.87031901 6.58328494]
